title: "【错误报告】"
labels: bug
name: "🐞 错误报告"
description: 创建报告以帮助我们改进
body:
  - type: markdown
    attributes:
      value: |
        **开始之前...**

        此表单仅用于提交错误报告。如果您有使用问题
        或者不确定这是否真的是一个错误，请确保：

        - 已更新到最新版本
        
        还要尝试搜索您的问题 - 它可能已经在 Issues 中得到解答甚至修复。
        但是，如果您发现旧的、已关闭的问题在最新版本中仍然存在，您应该使用下面的表单打开一个新问题，而不是对旧问题发表评论。
        
  - type: input
    id: os-version
    attributes:
      label: 操作系统版本
      description: 请提供您的操作系统名称和版本
      placeholder: 如：Windows 11 22H2 / macOS 14.1 / Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: cursor-version
    attributes:
      label: Cursor 版本
      description: 请提供您使用的 Cursor IDE 版本号
      placeholder: 如：0.46.8
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
      description: |
        请提供以下信息：
        1. 对错误的清晰简洁描述
        2. 错误发生时您正在执行的操作
        3. 错误复现的步骤
        4. 实际结果与预期结果的差异
        
        建议提供以下截图（如适用）：
        - 运行终端的错误输出截图
        - 经过脱敏的浏览器控制台错误截图（请确保已移除敏感信息）
        - 问题发生时的界面截图
      placeholder: |
        例如：
        1. 我在尝试使用自动注册功能时遇到错误
        2. 点击注册按钮后，页面一直处于加载状态
        3. 终端显示连接超时错误
        4. 预期应该完成注册流程，但实际卡在了加载页面
        
        [在此处插入相关截图]
    validations:
      required: true