title: "【功能请求】"
labels: enhancement
name: "✨ 功能请求"
description: 提出一个新的功能建议或改进意见
body:
  - type: markdown
    attributes:
      value: |
        **开始之前...**

        感谢您为项目提出新的功能建议！在提交功能请求之前，请：

        - 搜索现有的 Issues，确保没有重复的功能请求
        - 确保您使用的是最新版本
        - 考虑该功能是否真的对大多数用户有帮助
        
  - type: textarea
    id: problem-description
    attributes:
      label: 相关问题描述
      description: 请描述这个功能请求是为了解决什么问题，或者满足什么需求？
      placeholder: |
        例如：当我使用...功能时，发现缺少...这样的选项。
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 描述您希望看到的解决方案。请尽可能详细地说明该功能应该如何工作。
      placeholder: |
        例如：
        1. 添加一个新的按钮/选项，可以自动执行...
        2. 在设置页面增加...配置项
        3. 功能应该可以...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案
      description: 描述您考虑过的任何替代解决方案或功能。
      placeholder: |
        例如：
        - 使用第三方工具...但是不够方便
        - 手动操作可以实现，但效率太低
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 补充说明
      description: |
        添加任何其他上下文、截图或功能示例链接。
        如果您有具体的实现建议或参考案例，也可以在这里说明。
      placeholder: |
        可以包括：
        - 功能示意图
        - 类似软件中的相似功能截图
        - 参考链接
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 提交功能请求前，请确认以下内容
      options:
        - label: 我已经搜索过现有的 Issues，确认这不是一个重复的功能请求
          required: true
        - label: 我认为这个功能会对大多数用户有帮助
          required: true 